In [20]:
from statsmodels.datasets import get_rdataset

USArrests = get_rdataset('USArrests').data
USArrests.head()

Murder  Assault  UrbanPop  Rape
rownames                                   
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

In [33]:
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=True,
                        with_std=True,
                        copy=True)


scaler.fit(USArrests)
X_std = scaler.transform(USArrests)

euclidean_dist = pairwise_distances(X_std) ** 2

correlation_matrix = np.corrcoef(X_std)

corr_distance = 1 - correlation_matrix

print("Euclidean distance (first 5 rows, first 5 columns):")
print(euclidean_dist[:5, :5])

print("\nCorrelation-based distance (first 5 rows, first 5 columns):")
print(corr_distance[:5, :5])

Euclidean distance (first 5 rows, first 5 columns):
[[ 0.          7.4594756   5.36758447  1.69756151 10.86519304]
 [ 7.4594756   0.          7.44231842  8.14948396  9.26061863]
 [ 5.36758447  7.44231842  0.          7.53694915  1.75241723]
 [ 1.69756151  8.14948396  7.53694915  0.         14.45407425]
 [10.86519304  9.26061863  1.75241723 14.45407425  0.        ]]

Correlation-based distance (first 5 rows, first 5 columns):
[[0.         0.71383078 1.44659478 0.08774168 1.86592233]
 [0.71383078 0.         0.83072459 0.36727856 0.81371281]
 [1.44659478 0.83072459 0.         1.17665542 0.29490175]
 [0.08774168 0.36727856 1.17665542 0.         1.58631264]
 [1.86592233 0.81371281 0.29490175 1.58631264 0.        ]]
